[project]
name = "AuthMicroservices"
version = "0.0.1"
description = "AuthMicroservices for iot-backend"
dependencies = [
    "flask",
    "flask-sqlalchemy",
    "pymysql"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"