[project]
name = "iotauth"
version = "0.0.1"
description = "auth module for iot-backend"
dependencies = [
    "flask",
    "flask-cors",
    "flask-sqlalchemy",
    "sqlalchemy",
    "pymysql",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"